
DROP TABLE IF EXISTS prodotti;
DROP TABLE IF EXISTS eventi;
DROP TABLE IF EXISTS prenotazioni;
DROP TABLE IF EXISTS commenti;
DROP TABLE IF EXISTS admin;

CREATE TABLE prodotti(
	idprodotto INT(6) PRIMARY KEY NOT NULL auto_increment,	
	titolo VARCHAR(100) NOT NULL,			
	tipoalc VARCHAR(64) NOT NULL,			
	tipologia VARCHAR(64) NOT NULL,			
	gradazione INT(3) NOT NULL, 			
	regione VARCHAR(60) NOT NULL, 			
	temp VARCHAR(15) NOT NULL,				
	aroma VARCHAR(100) NOT NULL, 			
	desc_prod VARCHAR(2000) NOT NULL,
	alt VARCHAR(200) DEFAULT NULL,
	immagini LONGBLOB DEFAULT NULL,
	INDEX(titolo)
);

CREATE TABLE eventi (
	idevento INT(11) PRIMARY KEY NOT NULL auto_increment,
	evento VARCHAR(255) NOT NULL,	
	desc_evento VARCHAR(3000) NOT NULL,			
	dataZ DATE NOT NULL,							
	posti INT(4) NOT NULL,
	alt VARCHAR(200) DEFAULT NULL,
	imgeventi LONGBLOB DEFAULT NULL,						
	INDEX(dataz)										
);


CREATE TABLE prenotazioni (
	idprenotazione INT(11) PRIMARY KEY NOT NULL auto_increment,
	dataevento DATE NOT NULL,
	nominativo VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
	nposti INT(6) NOT NULL
);

CREATE TABLE commenti (
	nominativo VARCHAR(255) NOT NULL,
	email VARCHAR(255) PRIMARY KEY NOT NULL,
	oggetto VARCHAR(3000) NOT NULL,
	datacommento DATE NOT NULL
	);

CREATE TABLE admin (				
    username VARCHAR(50) NOT NULL UNIQUE,
    passwordz VARCHAR(64) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO `eventi` (`idevento`, `evento`, `desc_evento`, `dataZ`, `posti`, `alt`, `imgeventi`) VALUES
(1, 'Da Bassano a Tokyo a ritmo di cocktail', 'Tokyo International Barshow: uno degli eventi pi&ugrave; attesi in Giappone. Due giorni di esibizioni durante i quali i pi&ugrave; importanti bartender mondiali si sfideranno a ritmo di cocktail deliziando i presenti con le loro creazioni.\r\nSpecial guest dell\'evento i mixologist Mr. Julio Bermejo, noto a livello mondiale per il suo &quot;Tommy\'s Margarita&quot;, e Mr. Ian Burrell, vincitore del premio Best International Spirits Ambassador nella competizione Annual Spirited Awards.\r\nAd approdare in territorio nipponico anche i nostri prodotti, fieri protagonisti della performance di Mr. Nishida che li reinterpreter&agrave; secondo il proprio stile e la propria filosofia del bere miscelato.\r\nCuriosi di scoprire quali cocktail Mr. Nishida realizzer&agrave; con i prodotti Nardini?\r\nNon perdetevi l\'evento: il 30 gennaio dalle 11:00 alle 18:30, Prism Hall, Tokyo Dome City.', '2020-01-30', 50, 'Grapperia Nardini, Ponte Vecchio, Bassano', 0x4e617264696e6920283131292e6a7067),
(2, 'Tales of the cocktail: amari e liquori Nardini in viaggio', 'Un appuntamento imperdibile quello del prossimo 17 marzo, per veri appassionati del bere miscelato.\r\nTre dei principali esponenti del mondo mixology vi guideranno alla scoperta delle origini, delle influenze culturali e delle differenze organolettiche che caratterizzano liquori e amari, passando attraverso le loro diverse componenti aromatiche e tecniche di lavorazione. Un\'occasione importante per scoprire come esaltare il profilo organolettico dei propri cocktail e per creare una vera e propria esperienza di gusto.\r\nFrancesco Lafranconi, Avery Glasser ed Erik Lorincz vi sveleranno nuove tecniche di degustazione finora rimaste inedite e vi condurranno in un percorso alla scoperta delle origini e della tradizione degli amari e dei liquori italiani.\r\nDa non perdere!\r\nSave the date: 17 marzo, 15:00 - 16:30, Queen Anne Ballroom - Hotel Monteleone (214 Royal Street New Orleans, LA 70130)\r\n', '2020-03-17', 35, 'Bancone con prodotti Nardini per cocktail', 0x56696e6974616c79323031355f426c6f675f30312e6a7067),
(3, 'Nardini presenta Jazzy Christmas', ' Il 15 dicembre vi aspetta una serata all\'insegna del grande jazz in compagnia di Paolo Fresu Quintet e Daniele di Bonaventura.\r\nIl concerto si terr&agrave; al Garage Nardini a partire dalle ore 19:00, laboratorio creativo che nasce dalla distilleria dismessa con l\'obiettivo di ospitare artisti, dare visibilit&agrave; alla creativit&agrave; nazionale e internazionale e valorizzare il territorio.\r\nIn questa occasione saliranno sul palco di Garage Nardini Paolo Fresu Quintet e Daniele di Bonaventura, esponenti di spicco dello scenario jazz italiano e internazionale, che si esibiranno in uno spettacolo indimenticabile, in sintonia con l\'atmosfera delle feste in arrivo.\r\nA seguire, un dopoconcerto in compagnia degli artisti e del meglio della mixology firmata Nardini.', '2019-12-15', 27, 'Lounge bar, veduta bancone', 0x6a617a7a2d6573746174652d66726f6e742d706167652e6a7067),
(4, 'La nuova selezione Bortolo Nardini presentata alla 51esima edizione di Vinitaly', 'Il 12 aprile torna l\'imperdibile appuntamento con Vinitaly, il Salone Internazionale dei vini e dei distillati, quest\'anno alla sua 51esima edizione. &quot;Durante la kermesse veronese verr&agrave; presentata in anteprima la nuova linea &quot;Selezione Bortolo Nardini&quot;; dedicata esclusivamente al mercato Horeca. Una grande novit&agrave; che nasce dall\'esperienza di oltre due secoli della Famiglia Nardini nell\'arte distillatoria e che ha origine da un percorso iniziato 20 anni fa, con la scelta delle grappe pi&ugrave; morbide, profumate e dolci, ottenute da vinacce freschissime ed esclusivamente diraspate. Un\'attenta selezione tra oltre 4 milioni di litri di distillato conservati nelle cantine dell\'azienda, per ottenere dei prodotti unici e racchiuderli in bottiglie dai tratti futuristi ispirate alla sede aziendale, &quot;Bolle&quot;, realizzata dall\'architetto Massimiliano Fuksas.\r\nDurante queste giornate potrete scoprire e degustare in anteprima la nuova &quot;Selezione Bortolo Nardini&quot; e assaporare i prodotti pi&ugrave; classici: l\'iconica Grappa Bianca 50 gradi, la Tagliatella, l\'elegante Acqua di Cedro e gli aperitivi e bitter tra cui il celebre Mezzo-e-mezzo.\r\nNon mancheranno gli appuntamenti con il bere miscelato in compagnia di alcuni tra i migliori bartender del panorama italiano e internazionale. Samuele Ambrosi, Christian Lorenzato e Mauro Uva vi proporranno i loro cocktail e vi condurranno alla scoperta della grappa e dei nostri prodotti in miscelazione.\r\nSAVE THE DATE: 12 aprile - Padiglione 3, Stand B6 - Veronafiere.', '2020-04-12', 100, 'Padiglione Nardini, vinitaly a Verona', 0x363930313637353131345f336437333863383335305f622e6a7067),
(5, 'Degustazione di grappe e liquori trentini', 'Categoria: Enogastronomia. \r\nLocalit&agrave;: Levico Terme.\r\nData: Marted&igrave; 2 marzo ore 19:00.\r\nImporto dell\'attivit&agrave; :\r\n &euro; 10 a persona,\r\n &euro; 7 con Valsugana Card.\r\nNOTE: Ritrovo in centro a Levico presso &quot;Il Ponte dei Sapori&quot;. Prenotazioni entro le ore 18:00 del giorno precedente dell\'attivit&agrave;.', '2020-03-02', 21, 'Emporio grappe e distillati, zona degustazione', 0x31373236343138335f313239323139393037303831353534325f383937323637383533323534393732373636345f6e2e6a7067),
(6, 'Distilleria Marzadro', 'Proposte visite guidate e degustazioni.\r\nUn\'ospitalit&agrave; tutta trentina quella della Famiglia Marzadro, che assieme ai suoi collaboratori sar&agrave; lieta di accompagnarvi alla scoperta del pi&ugrave; tipico distillato d\'Italia: la Grappa. All\'interno ad accogliervi lo spettacolo degli alambicchi in rame, il silenzio delle sale d\'invecchiamento dove la Grappa riposa per anni, le sale dedicate alla degustazione guidata ed infine il punto vendita dove potrete scegliere un ricordo da condividere con le persone pi&ugrave; care.\r\n\r\nVISITA GUIDATA &quot;I CINQUE SENSI&quot;:\r\nPresentazione della Famiglia Marzadro e racconto storico.\r\nVisita alla distilleria ripercorrendo le diverse fasi produttive della Grappa: sala degli alambicchi, zone di stoccaggio, sale d\'invecchiamento.\r\nEsperienza sensoriale delle Grappe in affinamento nelle botti. Degustazione guidata con abbinamenti armoniosi e audaci tra Grappa e cioccolato Domori. Accompagnamento con Trentingrana, pane/grissini.\r\nDurata: 80 minuti.\r\nCosto a persona: &euro; 10 (massimo 15 persone).\r\nPer chi desidera un accompagnamento sfizioso: merenda di prodotti tipici trentini al costo aggiuntivo di 5 &euro; a persona.', '2019-12-10', 17, 'Sala alambicchi tenuta Marzadro', 0x6d61727a6164726f204e4f472e6a7067),
(7, 'Bardolino e castagne', 'Quando: 10/10/2019.\r\nA San Zeno di Montagna il primo di quattro appuntamenti per scoprire il vino che meglio si abbina ai piatti della tradizione e ai profumi della stagione.\r\nIl Bardolino, assieme ai marroni di San Zeno DOP, alle castagne del Monte Baldo e al formaggio Monte Veronese, sar&agrave; il protagonista di quattro appuntamenti dedicati ai sapori autunnali del monte Baldo, in programma a San Zeno di Montagna (Verona) a partire dal mese di ottobre. Di un luminoso colore rubino e con i suoi profumi di ciliegia, fragola, lampone, cannella, pepe e chiodo di garofano caratteristici dei vini rossi ottenuti prevalentemente dalle uve di Corvina Veronese, il Bardolino si sposa perfettamente con i piatti autunnali, a maggior ragione con quelli della tradizione del suo territorio d\'origine, il lago di Garda e il monte Baldo.\r\nAd aprire la stagione sar&agrave; la 22esima edizione della rassegna San Zeno Castagne, Bardolino e Monte Veronese, in programma il 10 ottobre, poi per tutto il mese cinque ristoranti proporranno dei men&ugrave; a base di castagne in abbinamento con il Bardolino. Tra i piatti della rassegna, il minestrone con verdure e marroni DOP proposto dal Ristorante al Cacciatore, gli gnocchi di farina di castagne e ricotta su pesto di ortiche con dadolata di zucca e salvia fritta del Ristorante Bellavista, le tagliatelle di zucca e castagne con ragout di carni bianche e scaglie di Monte Veronese preparate dal Ristorante Costabella, il capriolo con castagne e polenta del Ristorante Sole, la pancetta di maialino croccante con salsa ai marroni, pur&eacute; di pastinaca e pere caramellate da assaggiare alla Taverna Kus.', '2019-10-10', 67, 'Sacchetto di castagne e un calice di vino', 0x626172646f6c696e6f2d652d6361737461676e652e6a7067),
(8, 'Bassano Wine Festival', 'A Bassano del Grappa (Vicenza) si rinnova l\'evento dedicato al vino. Sabato 8 febbraio 2020 si svolger&agrave; la terza edizione di Bassano Wine Festival. La mostra mercato, che riunir&agrave; 70 cantine provenienti da tutta Italia, andr&agrave; in scena quest\'anno in una nuova location. Sar&agrave; infatti Villa Morosini Cappello, costruzione del \'500 d\'impronta palladiana situata a Cartigliano (Vicenza), ad ospitare gli eventi e gli incontri in programma per il pubblico, che potr&agrave; acquistare le etichette delle piccole realt&agrave; del mondo del vino e i prodotti degli artigiani della gastronomia che parteciperanno al Festival.\r\nQuest\'anno, inoltre, sar&agrave; possibile prendere parte alle degustazioni guidate dai sommelier di AIS Veneto, che si terranno, alle 14:30 e alle 17:00.\r\n&quot;Abbiamo lavorato per rendere l\'appuntamento con il Bassano Wine Festival - afferma Daniele Cavazzin, tra gli organizzatori dell\'evento - sempre pi&ugrave; ricco e coinvolgente. Anche quest\'anno quindi il programma comprender&agrave; masterclass, seminari e degustazioni guidate dedicate sia a esperti che ad appassionati&quot;.\r\nIl Bassano Wine Festival, nato nel 2017, si pone l\'obiettivo di valorizzare le realt&agrave; vitivinicole e le eccellenze gastronomiche di qualit&agrave;, in particolare quelle artigiane e poco conosciute. Un vero e proprio mercato del vino nel quale gli espositori possono mettere in vendita i propri prodotti e i visitatori degustare e acquistare direttamente dal produttore.\r\nOrario di apertura al pubblico: sabato dalle 14:00 alle 22:00 ; Ingresso: &euro; 20,00 ingresso per un giorno al Bassano Wine Festival comprensivo di accesso ai banchi d\'assaggio e degustazione di un piatto tipico realizzato in collaborazione con l\'Associazione Produttori Radicchio Rosso di Dosson\r\nParcheggio: gratuito.', '2020-02-08', 210, 'Logo Bassano Wine festival', 0x42617373616e6f2d353030783430302e6a7067),
(9, 'A Slow Wine Treviso, 88 cantine del Nord Est', 'La manifestazione Slow Wine Treviso &egrave; l\'occasione per degustare le etichette di 88 produttori vinicoli segnalati nell\'edizione 2019 della Guida Slow Wine. L\'appuntamento &egrave; il 27 gennaio 2020 a Treviso. In particolare, ai banchi d\'assaggio saranno protagonisti: Veneto, Friuli Venezia Giulia e Trentino Alto Adige. Inoltre, non mancher&agrave; una rappresentanza di cantine della Slovenia. In pi&ugrave;, come nelle precedenti edizioni, verr&agrave; dedicato spazio alle eccellenze gastronomiche degli &quot;Artigiani del Cibo&quot; selezionati da Slow Food Treviso.\r\nUn viaggio che si snoda dal Trentino Alto Adige, a Verona con le aree del Custoza, Bardolino, Valpolicella e Soave, al Vicentino e al Padovano con Breganze e i Colli Berici e Euganei, a Treviso con l\'Asolo Montello, le Colline del Prosecco e la zona del Piave, a Pramaggiore, proseguendo attraverso le Terre di Pianura e Le Colline Orientali del Friuli, il Collio, Isonzo e Carso, per concludersi nella vicina Slovenia.\r\nPer avere anche la possibilit&agrave; di acquistare i prodotti degli &quot;Artigiani del Cibo&quot;.\r\nInoltre, l\'area ristoro/degustazione, a cura di BHR Treviso Hotel, proporr&agrave; piatti tipici della cucina veneta preparati dallo staff del Ristorante DiVino Osteria Trevigiana. Sar&agrave; cos&igrave; possibile completare la visita con un pranzo domenicale che coniuga la cultura del vino e la tradizione alimentare all\'insegna dei princ&iacute;pi dettati da Slow Food.\r\nInfine, per sostenere le attivit&agrave; educative di Slow Food e della Fondazione per la Biodiversit&agrave;. Costo ingresso: ai visitatori verr&agrave; richiesto un contributo all\'associazione di 10 euro, comprensivo di degustazione dei vini e dei prodotti agroalimentari in esposizione e in vendita presso gli stand degli artigiani del gusto, e del calice e porta-calice con il logo di Slow Food.\r\nOrario: dalle ore 10:30 alle ore 19:00.', '2020-01-27', 45, 'Logo Slow wine', 0x536c6f7757696e65323031395f444c2e6a7067),
(10, 'Calici di Stelle: la notte di San Lorenzo a Barbarano Vicentino', 'Torna puntuale a Barbarano Vicentino l\'atteso evento &quot;Calici di Stelle&quot;, promosso dal Movimento Turismo del Vino e dall\'associazione Citt&agrave; del Vino e organizzato in collaborazione con la Pro Colli Berici, il Comune e l\'Ufficio Turistico di Barbarano Vicentino. &quot;Nella magica notte di San Lorenzo, il 10 agosto, in Piazza Roma, una serata dedicata all\'assaggio e alla degustazione di vini e specialit&agrave; gastronomiche prodotte dalle aziende del nostro territorio con passione e dedizione.\r\nL\'evento, che riunisce da anni milioni di enoappassionati in moltissime piazze d\'Italia, a Barbarano Vicentino prender&agrave; il via alle 19:00, quando in cassa sar&agrave; possibile ritirare il calice ed acquistare un carnet di ticket degustazione da consegnare alle cantine presenti, che quest\'anno saranno 22 e saranno come sempre liete di accogliervi e raccontarvi i loro vini, le loro storie, i loro segreti in una notte cos&igrave; magica. Sar&agrave; inoltre possibile assaggiare diversi piatti tipici e specialit&agrave; del territorio grazie alla presenza di ristoranti e aziende che presenteranno le loro delizie culinarie da abbinare al protagonista indiscusso della serata, il vino dei Colli Berici.\r\nLa manifestazione, che si svolger&agrave; in contemporanea in tutta la penisola con una serie di eventi enogastronomici e artistici, vedr&agrave; anche la partecipazione a Barbarano della Sound Art Orchestra, impegnata nel regalarci una serata di intrattenimento musicale con musica swing anni \'50. Per la serata, sar&agrave; aperto inoltre alle visite il Palazzo dei Canonici.\r\nEcco quali dei nostri Soci saranno presenti per farvi assaggiare i loro vini: &quot;Ca\' Basso, C&agrave; Rovere&quot;\r\nCantina Mattiello (Costozza di Longare)\r\nCostalunga (Castegnero)\r\nDal Maso (Montebello Vicentino)\r\nFattoria Le Vegre\r\nMiolato Rudy (San Germano dei Berici)\r\nNani 1967 (Tenuta Castello di Rubaro, Nanto)\r\nPiovene Porto Godi', '2020-08-10', 300, 'Veduta notturna di un bar', 0x63616c6963695f736f74746f5f6c655f7374656c6c655f6c6162726f5f74722e6a7067),
(11, 'Serata Degustando Nardini', 'Drink shop Desenzano ospiter&agrave; una serata SPECIALE NARDINI. Dalle ore 19:45 un professionista di Nardini, la pi&ugrave; antica distilleria d\'Italia dal 1779, ci far&agrave; viaggiare nella storia di questa antica azienda.\r\nLa serata prevede: Presentazione aziendale;\r\nAssaggio della gamma di prodotti;\r\nPossibilit&agrave; di confrontarsi su degustazione e realizzazione di cocktails.\r\nIl costo della serata &egrave; di 5 &euro; , che ti verranno scontati se acquisterai prodotti Nardini. Inoltre per i partecipanti sono previsti simpatici gadgets.', '2020-03-26', 30, 'Interno Grapperia Nardini, veduta scaffali', 0x4e617264696e6920283130292e6a7067),
(12, 'Serata degustazione grappe Poli', 'Gioved&igrave; 20 Febbraio, ore 21:30.\r\nUn appassionato viaggio attraverso i prodotti della storica distilleria Poli Grappa di Schiavon (VI).\r\nRelatore della serata: Domenico COZZUPOLI, esperto in distillati e promoter distilleria Poli.\r\nDurante la serata assaggeremo: \r\nAperitivo: Capo Nord con &quot;Airone Rosso&quot; e gin &quot;Marconi 46&quot;, le grappe classiche: &quot;Sarpa bianca&quot;, &quot;Sarpa barrique&quot;,\r\n&quot;Le grappe monovitigno&quot;, &quot;Morbida Po\'&quot;,\r\n&quot;Elegante Po\'&quot;. Le barricate,\r\n&quot;Cleopatra Amarone&quot;, &quot;2 Barili&quot;,\r\n&quot;Il vermut&quot;, &quot;Gran Bassano Rosso&quot;.\r\nDurante la degustazione accompagnamento con stuzzichini e piatti caldi e freddi. Un dessert accompagner&agrave; l\'ultima proposta.', '2020-02-20', 55, 'Logo Degustazione grappe Poli', 0x37313039333136355f323735313737353230313531333431355f373933333932333730303938303538303335325f6e2e6a7067);


INSERT INTO `prodotti` (`idprodotto`, `titolo`, `tipoalc`, `tipologia`, `gradazione`, `regione`, `temp`, `aroma`, `desc_prod`, `alt`, `immagini`) VALUES
(1, 'Poli Bassano Classica', 'Grappa', 'Giovane', 40, 'Veneto', '15', 'mela cotogna, prugna secca', 'Questa Grappa giovane, nasce dalla distillazione di una cuvet di vinacce di vitigni tipici della zona di Bassano del Grappa. Il suo sapore &egrave; armonico e amabile con aromi fruttati di mela cotogna e prugna secca.', 'Grappa giovane Poli Bassano Classica', 0x62617373616e6f2d636c6173736963612e6a7067),
(2, 'Marolo Acquavite di Pere', 'Grappa', 'Giovane', 40, 'Veneto', '10', 'profumo delicato e rotondo di pera matura, sapore secco fruttato', 'Questa Grappa giovane viene affinata vasche in acciaio inox, &egrave; contraddistinta da un netto riconoscimento del frutto. Il suo sapore si abbina perfettamente con dolci da forno', 'Grappa giovane Marolo Acquavite di Pere', 0x4163717561766974655f64695f706572652e6a7067),
(3, 'Grappa Nonino Chardonnay', 'Grappa', 'Barricata', 41, 'Veneto', 'ambiente', ' Fine ed elegante, profumo di pane e vaniglia ', 'Realizzata con vinacce fresche di uva Chardonnay da zone vocate, distillazione discontinua, con il taglio delle teste e delle code, in alambicco in rame a vapore, &egrave; caratterizzata dal gusto fine ed elegante, sentore di cioccolata e mandorle appena sgusciate.', 'Grappa barricata Nonino Chardonnay', 0x6e6f6e696e6f5f63686172646f6e6e61792e6a7067),
(5, 'Grappa Culto Gewurztraminer', 'Grappa', 'Barricata', 40, 'Veneto', '7', 'morbida, calda e equilibrata', 'Realizata con vinacce di uve Traminer, &egrave; caratterizzata da un colore limpido giallo dorato, profumo coinvolgente che si integra con note vanigliate e legnose. Sensazioni delicate di raffinatezza in un elegante equilibrio, viene invecchiata in legno pregiato.', 'Grappa barricata Culto Gewurztraminer', 0x63756c746f5f726f7373696461736961676f2e6a7067),
(6, 'Grappa Poli Due Barili', 'Grappa', 'Barricata', 40, 'Veneto', '18', 'cioccolato al latte, uva passa e nocciole tostate', 'La Grappa Poli Due Barili ha un sapore particolarmente ricco e morbido, grazie a un armonioso blend di Grappa da Prosecco e pura vinaccia dall\'aroma floreale, oltre al doppio invecchiamento in due tipi di barili diversi: almeno due anni in Barrique di Rovere Francese da 225 litri e almeno due anni in barili di Sherry PX.', 'Grappa barricata Poli Due Barili', 0x6475652d626172696c692e6a7067),
(7, 'Grappa Poli Cleopatra Amarone ', 'Grappa', 'Barricata', 40, 'Veneto', '18', 'frutta secca, spezie (vaniglia e cacao), legno fresco lievemente', 'Nasce dalla distillazione delle vinacce di Corvina, Rondinella e Molinara per Amarone della Valpolicella. Ottenuta utilizzando Crysopea, il nostro innovativo alambicco a bagnomaria sotto vuoto, la Grappa Cleopatra Amarone Oro profuma di frutta secca, spezie dolci e legno tostato, e rivela un sapore pieno e sincero.', 'Grappa barricata Poli Cleopatra Amarone', 0x636c656f70617472612d616d61726f6e652d6f726f2e6a7067),
(12, 'Grappa Poli Liquirizia', 'Grappa', 'Aromatizzata', 40, 'Veneto', '10', 'fragrante di spezie e foglia di the', 'Prodotta da vinacce tipiche della zona. La radice messa in infusione all\'interno della bottiglia crea una combinazione di aromi speziati, fra cui si nota la foglia di the, con un contrasto piacevole tra il dolce e l\'amaro', 'Grappa aromatizzata Poli alla Liquirizia', 0x706f6c692d6c6971756972697a69612e6a7067),
(13, 'Rossi d\'Asiago Grappa al Mirtillo', 'Grappa', 'Aromatizzata', 38, 'Veneto', '10-12', 'calda, dolce e leggermente acidula.', 'Realizzata da uve di selezionati vitigni veneti. Le propriet&agrave; officinali del mirtillo sono infuse in questa grappa particolare, dal sapore estremamente gradevole, adatto ad ogni situazione di consumo. Il suo aspetto &egrave; di colore vermiglio trasparente, &egrave; definito da una forte intensit&agrave; con note fruttate e sentori aspri agrumati', 'Grappa aromatizzata Rossi d\'asiago al mirtillo', 0x726f7373695f6d697274696c6c6f2e6a7067),
(14, 'Poli Amaro Vaca Mora', 'Liquore', 'Speziato', 32, 'Veneto', '15', ' speziato e lieve di menta', 'Amaro ottenuto per infusione in Grappa e alcool di erbe aromatiche. Il suo gusto &egrave; amaro con aromi gradevolmente speziati e una nota rinfrescante di menta.', 'Liquore speziato Poli Amaro Vaca Mora', 0x616d61726f2d766163612d6d6f72612e6a7067),
(15, 'Marolo Liquore alla Camomilla', 'Liquore', 'Speziato', 35, 'Veneto', 'ambiente', 'caldo e avvolgente', 'Liquore ottenuto dall\'infusione dei capolini della camomilla in grappa di Nebbiolo. Ha un effetto corroborante sulla digestione con propriet&agrave; calmanti. &Egrave; ottenuta seguendo una delle ricette di Langa pi&ugrave; tradizionali e semplici.', 'Liquore speziato Marolo Liquore alla Camomilla', 0x6d61726f6c6f5f63616d6f6d696c6c612e6a7067),
(16, 'Marolo Amaro Ulrich', 'Liquore', 'Distillato', 32, 'Veneto', 'ambiente', 'pungente e aromatico', 'L\'Amaro Ulrich nasce nel 1854 dalla ricetta del Dottor Domenico Ulrich ed oggi viene rielaborato dalla Distilleria Marolo, grazie ad anni di esperienza in campo liquoristico. L\'Amaro Ulrich racchiude principi attivi di 19 erbe, fiori, frutti e radici che lo rendono un\'efficace e corroborante digestivo. Tra i vari ingredienti spiccano le note di genepi, della genziana e dell\'anice: &egrave; proprio dalla naturalit&agrave; della sua formulazione che nasce il suo carattere unico ed inconfondibile. I sistemi di lavorazione ancora del tutto tradizionali esulano da schemi moderni e mantengono inalterati i principi attivi ed aromatici che caratterizzano il prodotto.', 'Liquore distillato Marolo Amaro Ulrich', 0x616d61726f5f756c726963682e6a7067),
(17, 'Rossi D\'Asiago Sanbuca alla Mela', 'Liquore', 'Distillato', 38, 'Veneto', 'ambiente', 'Armonioso, emerge l\'anice e sentori di mela.', '&Egrave; un liquore a base di Antica Sambuca Classic e aroma di mela, di colore verde brillante e un profumo intenso di mela. Il sapore &egrave; armonioso, emerge delicatamente l\'anice e sul finire sentori di mela. Pu&ograve; essere gustata liscia, con ghiaccio o come ingrediente per la preparazione di cocktail e long drink. Viene prodotta anche nelle varianti al lampone, liquirizia, banana, mela e caff&egrave;.', 'Liquore distillato Rossi d\'Asiago Sanbuca alla Mela', 0x73616e627563615f6d656c612e6a7067),
(18, 'Rossi D\'Asiago Amaro Asiago', 'Liquore', 'Distillato', 30, 'Veneto', 'ambiente', 'Dolce e amaro con una nota predominante di genziana', 'Amaro digestivo a base di infusi di erbe e radici, da consumare dopo i pasti a temperatura ambiente o con ghiaccio', 'Liquore distillato Rossi d\'Asiago Amaro Asiago', 0x616d61726f5f61736961676f2e6a7067),
(19, 'Poli Elisir Prugna', 'Liquore', 'Fruttato', 40, 'Veneto', '12', 'fruttato e ammandorlato', 'La caratteristica di questo elisir &egrave; dovuta all\'infusione in alcool di puro succo di prugna. Il suo sapore &egrave; piuttosto dolce e fruttato con una sublime nota di amaretto. Consigliato anche nella correzione del caff&egrave;.', 'Liquore fruttato Poli Elisir Prugna', 0x706f6c692d707275676e612e6a7067),
(20, 'Giordano Barbaresco D.O.G.G.', 'Vino', 'Rosso', 14, 'Veneto', '19', 'note di marasca, spezie e vaniglia.', 'Nasce da uva Nebbiolo, un vitigno esigente che richiede terreni fertili e profondi e predilige le colline di ripida pendenza. Viene vinificato tradizionalmente, con lunghe macerazioni delle bucce, e poi affinato per almeno 3 anni in botti di rovere, in cantine con luce, umidit&agrave; e temperatura costante.', 'Vino rosso Giordano Barbaresco', 0x67696f7264616e6f5f6261726261726573636f2e6a7067),
(21, 'Colli Euganei Cabernet Sauvignon', 'Vino', 'Rosso', 14, 'Veneto', '19', 'strutturato e persistente', 'Profumo di frutta rossa ben amalgamato ad un corpo di buona struttura. Piacevole da giovane, austero ed elegante se affinato. Vino di lunga vita ideale con arrosti e spiedi, con Asiago d\'allevo stagionato e polenta abbrustolita o con costolette d\'agnello alla brace. Presente anche nella versione Riserva.', 'Vino rosso Colli Euganei Cabernet Sauvignon', 0x636f6c6c695f63616265726e65742e6a7067),
(22, 'Colli Euganei Fior D\'Arancio Spumante', 'Vino', 'Bianco', 6, 'Veneto', '8', 'dolce, salvia e albicocca', 'Vino tipico dei Colli Euganei dal sapore dolce, ideale per dolce o per aperitivi, caratterizzato da sentori mediterranei, aromi citrini, di zagara, di salvia e di albicocca presenta una gradazione alcolica bassa, intorno ai 6 gradi, e invita a berne un secondo bicchiere', 'Vino bianco Colli Euganei Fior d\'Arancio Spumante', 0x7370756d616e74652e6a7067),
(23, 'Colli Euganei Fiori D\'Arancio Passito', 'Vino', 'Bianco', 6, 'Veneto', '6', 'dolce e aromatico ', 'Dal colore giallo solare con profondi riflessi dorati, sprigiona un intenso profumo di albicocche mature, di miele, di frutta candita e di spezie. Il sapore &egrave; dolce ed equilibrato, intensamente aromatico, persistente. Indimenticabile &egrave; ogni suo incontro con gli Zaleti (biscotti a base di farina di mais e uvetta). In libera uscita, sta stringendo amicizia con qualche formaggio erborinato e con tartine al foie gras.', 'Vino bianco Colli Euganei Fiori d\'Arancio Passito', 0x636f6c6c695f7061737369746f2e6a7067),
(24, 'Giordano Asti Spumante', 'Vino', 'Bianco', 7, 'Veneto', '6', 'aromatico, moscato', 'Colore paglierino carico, con perlage fine e persistente; profumo intenso ed aromatico, piacevolmente frizzante; il sapore &egrave; un perfetto equilibrio fra l\'aroma tipico del Moscato e la pienezza del gusto, ottenuta con una speciale vinificazione. Perfetto per le feste e i brindisi, nato per accompagnare i dolci e i dessert.', 'Vino bianco Giordani Asti Spumante', 0x67696f7264616e6f5f617374692e6a7067),
(25, 'Amarone della Valpolicella D.O.C.G.', 'Vino', 'Rosso', 15, 'Veneto', '18', 'frutta matura a bacca rossa', 'L\'Amarone della Valpolicella D.O.C.G. &egrave; ottenuto da uve raccolte manualmente e appassite su graticci per un periodo di tempo non inferiore ai tre mesi, a temperatura e umidit&agrave; controllate. Dopo la fermentazione, momento chiave per la definizione del suo carattere, matura per almeno due anni in botti di rovere e successivamente riposa in bottiglia per altri 12 mesi. Si sposa alla perfezione con piatti a base di carni rosse, selvaggina, formaggi stagionati e saporiti.', 'Vino rosso Amarone della Valpollicella', 0x616d61726f6e655f76616c706f6c6963656c6c612e6a7067),
(26, 'Ca\' Merletto Bianco Veneto I.G.T. ', 'Vino', 'Bianco', 12, 'Veneto', '12', 'sentori floreali, note di frutta a polpa bianca, mela e pera', 'Vino fresco e invitante, con tutta la grazia di una regione piena di meraviglie. Vinificato con scrupolose attenzioni, restituisce all\'assaggio un corredo aromatico ampio e sempre stimolante; proprio come i merletti di Venezia, realizzati con perizia da esperte artigiane, questo vino rappresenta il tocco di classe dei nostri Wine Makers, capaci di scrivere con grazia una pagina importante nel grande libro del vino italiano.', 'Vino bianco Ca\' Merletto', 0x63615f6d65726c6574746f2e6a7067),
(27, 'Pinot Grigio delle Venezie D.O.C.', 'Vino', 'Bianco', 12, 'Veneto', '8', 'note aromatiche e sentori di mela verde', 'Di gran piacevolezza di beva vista la morbidezza della sua polposa albicocca matura. Un vino eccellente giacch&eacute; anche ben fitto e di mirabile integrit&agrave; enologica esecutiva.', 'Vino bianco Pinot Grigio delle Venezie', 0x70696e6f742e6a7067),
(28, 'Nardini Acquavite di Vinaccia', 'Grappa', 'Giovane', 60, 'Veneto', 'ambiente', 'immediato, fragrante, determinato.', 'Corposa, pulita e persistente. Una grappa trasparente e cristallina, dall\'aroma avvolgente che anticipa l\'emozione del gusto intenso e pulito. Un insieme armonico di qualit&agrave; inimitabili che solo i legami pi&ugrave; profondi e duraturi possono regalare. Tutte le sfumature del gusto per stupire con un gesto.', 'Grappa giovane Nardini Acquavite', 0x6e617264696e695f6163717561766974652e6a7067),
(29, 'Nardini Grappa Riserva 15 anni', 'Grappa', 'Barricata', 45, 'Veneto', 'ambiente', 'Sentori di vaniglia, frutta matura, tabacco e cannella.', 'Intensa e molto persistente con sentori di vaniglia, frutta matura, tabacco e cannella. Nasce dall\'esperienza di oltre due secoli della famiglia Nardini nell\'arte distillatoria. Questa grappa ramata &egrave; invecchiata per almeno 15 anni in botti di Rovere di Slavonia.', 'Grappa barricata Nardini Grappa Riserva 15 anni', 0x6e617264696e695f3135616e6e692e6a7067),
(30, 'Nardini Grappa alla Genziana', 'Grappa', 'Aromatizzata', 43, 'Veneto', 'ambiente', 'amaro, aromatico', 'Intensa, aromatica ed amara. Questa grappa contiene la forza della radice di genziana che lo rende sia un perfetto digestivo sia un piacere armonico da gustare. Perfetta dopo i pasti, Aquavite di Vinaccia alla Genziana regala benessere e serenit&agrave; mentre si osserva in trasparenza il suo limpido color verde chiaro.', 'Grappa aromatizzata Nardini Grappa alla Genziana', 0x6e617264696e695f727574612e6a7067),
(31, 'Nardini Liquore alla Mandorla', 'Liquore', 'Fruttato', 50, 'Veneto', 'ambiente', 'intenso, secco, leggermente dolce al retrogusto.', 'Profumata, secca e dolce nel retrogusto. Una grappa che racchiude tutte le sfumature del gusto della mandorla, che unita al distillato di marasca, crea un perfetto equilibrio per chi vuole scoprire il mondo dei distillati miscelati e avvicinarsi a questi sapori.', 'Liquore fruttato Nardini Liquore alla Mandorla', 0x6e617264696e695f6d616e646f726c612e6a7067),
(32, 'Nardini Brandy', 'Liquore', 'Distillato', 42, 'Veneto', 'ambiente', 'intenso, deciso con note tostate riconducibili al legno e al cuoio', 'Morbido, raffinato ed intenso. Un gusto che prende forma grazie al lungo invecchiamento in botte. Le note tostate richiamano il legno e il cuoio, immediatamente percepibili fin dall\'aroma. Scaglie di cioccolato fondente e un buon sigaro possono aggiungere un dettaglio di gusto a questo momento di puro piacere.', 'Liquore distillato Nardini Brandy', 0x6e617264696e695f6272616e64792e6a7067),
(33, 'Nardini Liquore al Ginepro', 'Liquore', 'Speziato', 45, 'Veneto', 'fredda', 'note balsamiche delle bacche di ginepro', 'Intenso, balsamico e profumato. Ginepro Nardini nasce dall\'unione di semi di cumino dei prati, erbe e bacche di ginepro che impreziosiscono il gusto, donando intense note balsamiche. Un digestivo dall\'aroma dolce ed asciutto, versatile nell\'uso e perfetto da gustare miscelato.', 'Liquore speziato Nardini Liquore al Ginepro', 0x6e617264696e695f67696e6570726f2e6a7067),
(34, 'Nardini Tagliatella', 'Liquore', 'Fruttato', 35, 'Veneto', 'fredda', 'fruttato, armonioso nel rapporto dolce-amaro con una preponderanza di ciliegia.', 'Fruttato, speziato ed armonico. Un liquore unico, dalle sfumature floreali e fini note speziate. Grappa, marasca, arancio ed erbe sono alla base della ricetta gelosamente custodita dalla famiglia Nardini. L\'equilibrio di sapori dolci-amari stupisce anche i palati pi&ugrave; esigenti e conquista dal primo sorso.', 'Liquore fruttato Nardini Tagliatella', 0x6e617264696e695f7461676c696174656c6c612e6a7067),
(35, 'Luxardo Sangue Morlacco ', 'Liquore', 'Fruttato', 30, 'Veneto', 'freddo', 'intenso ed inebriante di marasche', '&quot;Il Liquore Cupo che alla mensa di Fiume chiamavo Sangue Morlacco &quot;\r\nGabriele D\'Annunzio.\r\nLiquore realizzato con succo delle marasche il quale stagiona in botti di rovere per almeno nove mesi prima di venire trasformato in liquore: esso ritorna poi nelle stesse botti per un periodo opportuno prima dell\'imbottigliamento.\r\nIl colore &egrave; rosso cupo con un profumo intenso ed inebriante di marasche ed un gusto corposo e molto rotondo al palato.\r\n\r\nSangue Morlacco pu&ograve; essere gustato liscio o con ghiaccio come fine pasto oppure come ingrediente in molti cocktail internazionali. &egrave; particolarmente indicato l\'abbinamento con cioccolato fondente, con frutti di bosco o sul gelato.', 'Liquore fruttato Luxardo Sangue Morlacco', 0x6c75786172646f5f6d6f726c6163636f2e6a7067),
(36, 'Luxardo Sour Cherry Gin', 'Liquore', 'Speziato', 38, 'Veneto', 'freddo', 'note di Gin, con sentore di ginepro armonioso', 'Luxardo Sour Cherry Gin &egrave; il risultato della perfetta combinazione tra il succo delle marasche Luxardo ed il London Dry Gin Luxardo. Un\'attenta selezione di nove &quot;botanici&quot; quali ginepro, coriandolo, iris, angelica, liquirizia, china, cannella, cardamomo e arancio amaro lasciati in infusione alcolica per 24 ore nei tradizionali alambicchi di rame a ciclo discontinuo prima della distillazione.\r\nDi colore rosso rubino, con tipiche note di Gin, con sentore di ginepro armonioso e note speziate. In fondo un avvolgente e morbido sentore di marasca con retrogusto lungo e persistente forza aromatica.\r\nSour Cherry Gin pu&ograve; essere usato come &quot;twist&quot; in molti cocktail classici come il Martinez o il Gin Fizz oppure bevuto liscio o con ghiaccio come dopo cena.', 'Liquore speziato Luxardo Sour Cherry Gin', 0x6c75786172646f5f736f75725f6368657272792e6a7067),
(37, 'San Matias Tahona Tequila', 'Liquore', 'Fruttato', 40, 'Veneto', 'fredda', 'richiami alla dolcezza dell\' Azul con la presenza di note minerali', 'San Matias Tahona Tequila &egrave; il risultato di 130 anni di esperienza e tradizioni consolidate nel tempo che riflettono la passione di Casa San Matias per la valorizzazione del Tequila tradizionale. Questo distillato &egrave; infatti il frutto di un piccolo lotto di produzione in cui si sono seguite alla lettera le tradizioni artigianali del Jalisco.\r\nPer conferire al distillato il massimo dell\'espressione della materia prima e della zona di provenienza, viene cotta a vapore in forni di pietra, molita con l\'autentica pietra circolare Tahona datata 1886, fermentata in vasche di legno e distillata in alambicchi di rame esattamente come si faceva secoli addietro.', 'Liquore fruttato San Matias Tahona Tequila', 0x7072696d657576655f74657175696c612e6a7067),
(38, 'Bonaventura Maschio Prime Uve Nere', 'Grappa', 'Aromatizzata', 40, 'Veneto', 'ambiente', 'note di frutti rossi, frutta secca e una gradevole sensazione di vaniglia', 'Questo elegante distillato nasce da pregiate uve nere, colte a maturazione inoltrata e lavorate secondo un metodo esclusivo, in cui la distillazione fatta sottovuoto garantisce l\'aromaticit&agrave; originaria. In seguito viene ingentilito da un periodo di affinamento in botti di legno.\r\nDegustato a temperatura ambiente, Prime Uve Nere esprime al meglio il suo ricco e delicato bouquet', 'Grappa aromatizzata Bonaventura Maschio Prime Uve Nere', 0x7072696d657576655f6e6572652e6a7067),
(39, 'Bonaventura Maschio Prime Uve Oro', 'Grappa', 'Giovane', 40, 'Veneto', 'ambiente', 'sensazioni fruttate e floreali, unite a un fine sentore di miele', 'Questo originale distillato nasce da pregiate uve bianche di collina, colte a maturazione inoltrata e lavorate secondo un metodo esclusivo, in cui la distillazione fatta sottovuoto garantisce l\'aromaticit&agrave; originaria.\r\nIn seguito viene ingentilito da un periodo di affinamento in botti di legno.\r\nSi consiglia di servirlo ad una temperatura di cantina', 'Grappa giovane Bonaventura Maschio Prime Uve Oro', 0x7072696d655f7576655f6f726f2e6a7067);


INSERT INTO `prenotazioni` (`idprenotazione`, `dataevento`, `nominativo`, `email`, `nposti`) VALUES
(1, '2020-03-17', 'Maria Grazia Gallo', 'mariagraziagallo@jourrapide.com', 2),
(2, '2020-03-17', 'Amedeo Lucchesi', 'amelucche@telew.us', 5),
(3, '2020-03-26', 'Ileana Ferrari', 'ile.ferrari88@armyspy.com', 4),
(4, '2020-03-26', 'Filiberto Siciliani', 'fil.sic.32@dayrep.com', 8),
(5, '2020-04-12', 'Clara Mancini', 'mancini.c@outlook.com', 3),
(6, '2020-08-10', 'Ferruccio Marchesi', 'ferr.march55@gmail.com', 10),
(7, '2020-03-02', 'Germana Milanesi', 'germymila66@yahoo.it', 6),
(8, '2020-08-10', 'Domenico Bellucci', 'bell_dome@libero.it', 5);

INSERT INTO `commenti` (`nominativo`, `email`, `oggetto`, `datacommento`) VALUES 
('Maria Grazia Gallo', 'mariagraziagallo@jourrapide.com', 'Buongiorno, ho prenotato 2 posti per l\'evento del 17 marzo. Vorrei sapere, per cortesia, se &egrave; possibile arrivare in ritardo rispetto all\'orario previsto per l\'evento perch&eacute; veniamo da lontano quindi non riusciamo ad arrivare in tempo. Grazie per le risposte che vorrete fornirmi.', '2020-01-15'),
('Giorgia Li Scalzi', 'lisc.33@libero.it', 'Salve, ho provato a chiamare al vostro negozio ma non mi ha risposto nessuno. Faccio questo tentativo nella speranza che qualcuno possa aiutarmi. Vorrei fare un regalo per un\'amica, nello specifico vorrei comprare l\'&quot;amaro ulrich&quot; e mi chiedevo se fosse disponibile in negozio. Poich&eacute; non sono della zona volevo sapere se fosse possibile riceverlo a casa o altrimenti mi organizzo per venire direttamente in negozio. Saluti. Giorgia.', '2020-01-20'),
('Gennaro Trentin', 'genn.tre@adex.it', 'Buonasera, sfrutto questo form per farvi le congratulazioni per l\'ultimo evento che avete organizzato! Ho trascorso una giornata fantastica con mia moglie all\'insegna del bere (bene!) e della compagnia di altri esperti di grappe... spero organizziate presto un\'altra rimpatriata col gruppo dello scorso evento. Buona giornata', '2020-01-17'),
('Silvia Cristofani', 'sil_cris@klaus.com', 'Buongiorno! Sono passata ieri in negozio e ho dimenticato a chiedervi una informazione molto importante. &Egrave; possibile portare mio figlio (minorenne) all\'evento del 4 aprile? So che &egrave; una richiesta un po\' strana anche perch&eacute; capisco che di solito questo tipo di eventi &egrave; frequentato per lo pi&ugrave; da adulti. Grazie per l\'attenzione, saluti.', '2020-01-01'),
('Lorenzo Pisani', 'lorenzo.pisani3@gmail.com', 'Buongiorno, ho dato un\'occhiata al vostro sito e sembra tutto davvero figo! Il prossimo febbraio mi laureo e stavo pensando di organizzare il rinfresco di laurea presso il vostro negozio. &Egrave; possibile fare questa cosa? Mitici.', '2020-01-05');

INSERT INTO admin(username, passwordz)
VALUES('admin', 'admin');
